### ISSUE TITLE
Tauri 2.0 Compatibility

### ISSUE THREAD

**Issue by appinteractive** [MatsDK/TauRPC#18]
Any change this project will work with tauri 2.0 (alpha)?

Currently I get following error:

```sh
cargo add taurpc
    Updating crates.io index
      Adding taurpc v0.2.3 to dependencies.
    Updating crates.io index
error: failed to select a version for `raw-window-handle`.
    ... required by package `tauri v1.3.0`
    ... which satisfies dependency `tauri = "^1.3"` of package `taurpc v0.2.3`
    ... which satisfies dependency `taurpc = "^0.2.3"` of package `freelance-metrics v0.0.0 (/Users/Greg/Projekte/Eigenes/FreelanceMetrics/src-tauri)`
versions that meet the requirements `=0.5.0` are: 0.5.0

all possible versions conflict with previously selected packages.

  previously selected package `raw-window-handle v0.5.2`
    ... which satisfies dependency `raw-window-handle = "^0.5"` of package `tauri v2.0.0-alpha.20`
    ... which satisfies dependency `tauri = "^2.0.0-alpha.20"` of package `tauri-plugin-fs v2.0.0-alpha.7 (https://github.com/tauri-apps/plugins-workspace?branch=v2#1b1d795b)`
    ... which satisfies git dependency `tauri-plugin-fs` (locked to 2.0.0-alpha.7) of package `freelance-metrics v0.0.0 (/Users/Greg/Projekte/Eigenes/FreelanceMetrics/src-tauri)`
```

**Comment by MatsDK** [comment]
Hi, I tried upgrading tauri to `v2.0.0-alpha.20` but it seems like there are some small changes that break TauRPC. I will try to see if there is an easy fix for this sometime. Because I don't know if there are more changes coming to the IPC API in v2.

**Comment by appinteractive** [comment]
As far as I understand, they are already in the auditing process before beta release. I hope there are no much updates 🤞

**Comment by MatsDK** [comment]
I create a new [branch](https://github.com/MatsDK/TauRPC/tree/tauri-v2) for this. And I published the `taurpc@0.3.0-alpha.1` crate to use TauRPC with `tauri v2.0.0-alpha.20`. And the client side library can be install with the `next` tag. 
```bash
cargo add taurpc@0.3.0-alpha.1
```
```bash
pnpm install taurpc@next
```

**Comment by MatsDK** [comment]
Now you can also use `tauri v2.0.0-beta.12`
```
cargo add taurpc@0.3.0-alpha.2
```
```
pnpm install taurpc@next
```
If you want to keep using the alpha version of tauri, make sure you install taurpc version `1.5.0` on the client side.

**Comment by jalcine** [comment]
Just checked on this before integrating it with a [project of mine](https://git.sr.ht/~jacky/shock/). Really nice work!

**Comment by super-fun-surf** [comment]
is there an update on tauri v2 support?

**Comment by bivald** [comment]
I have a very much work in progress to support the latest RC of Tauri at https://github.com/bivald/TauRPC/tree/tauri-v2 

Had to hack around a little bit in both rust and typescript to make it work.

Your mileage may vary :D

**Comment by MatsDK** [comment]
Now supporting the latest rc-version of tauri (`2.0.0-rc.10`).
```
cargo add taurpc@0.3.0-alpha.3
```

**Comment by Sun-ZhenXing** [comment]
@MatsDK Tauri v2 stable has been released, is there a corresponding TauRPC stable release planned?

**Comment by MatsDK** [comment]
I saw the Tauri v2 release and I will probably update TauRPC to support it this weekend. Thanks for letting me know.

**Comment by MatsDK** [comment]
Now supporting `tauri@2.0.0`. Install `taurpc@0.3.0` on the backend and upgrade to the latest version of taurpc on your frontend (`pnpm install taurpc@latest`).
