### ISSUE TITLE
cannot find struct, variant or union type `Invoke` in module `tauri::ipc`

### ISSUE THREAD

**Issue by MinionMax** [MatsDK/TauRPC#20]
First of all thank you for the library, I think it'll be really useful once i get it working!

I followed along to your quick start guide so I used the same dependency versions as you

```rs
// /src-tauri/src/api/api.rs → gets imported to main.rs
use taurpc::{ procedures, resolvers };
use crate::system::focus::Focus::{ Focus, FocusModeList };


#[derive(Clone)]
pub struct ApiImpl;

#[taurpc::procedures]
trait Api {
    async fn get_all_focus_modes();
}

#[taurpc::resolvers]
impl Api for ApiImpl {
    async fn get_all_focus_modes(self) -> FocusModeList {
        let focus_list = Focus::new().get_all_focus_modes(true);
        return focus_list;
    }
}
```

i get the following errors for the macro use:
<img width="1065" alt="Screenshot 2024-03-26 at 17 58 55" src="https://github.com/MatsDK/TauRPC/assets/69598926/8ce775d7-ab5d-4335-83d9-123cc5bd2a73">
<img width="1066" alt="Screenshot 2024-03-26 at 17 58 25" src="https://github.com/MatsDK/TauRPC/assets/69598926/a064d7a2-d8d3-467d-bd5f-1444a32dd97a">
I can see all the mentioned members defined ([Invoke](https://github.com/MatsDK/TauRPC/blob/87918689425d7e7dd32151fb0b0a8017a28f8f77/taurpc/taurpc-macros/src/generator.rs#L375) & [TauRpcHandler](https://github.com/MatsDK/TauRPC/blob/87918689425d7e7dd32151fb0b0a8017a28f8f77/taurpc/src/lib.rs#L23)) so I have no idea where this is coming from...
Am I missing something here or is it just a bug?

OS: MacOS Sonoma 14.4
Rustc: rustc 1.70.0 (90c541806 2023-05-31)
Tauri: version 1

**Comment by MatsDK** [comment]
Hi, I think this has something to do with the tauri v2 alpha version. If you are using tauri v1 you should install taurpc version `0.2.3`. 

If you want to use tauri v2 alpha, you can look at the branch in this repository I created for it.

I will look into this later and support newer beta versions of tauri. Hopefully this helps you.

**Comment by MatsDK** [comment]
Thanks for reporting this issue. The `taurpc` crate was using a newer dependency that was meant for tauri v2 support. 
You should be able to resolve your issue now by changing the taurpc version.
```
taurpc = "0.2.4"
```
