### ISSUE TITLE
type macro seems to disallow usage of doc comments

### ISSUE THREAD

**Issue by mnpqraven** [MatsDK/TauRPC#21]
I can't use both the `///` and `#[doc]` macro to comment my structs if i use the `ipc_type` macro.
Is there a workaround for this or am i missing something obvious

![image](https://github.com/MatsDK/TauRPC/assets/8957788/784f56fc-41e3-454e-9458-3e17242b08fe)

**Comment by MatsDK** [comment]
Thanks for reporting this issue. This is an [issue](https://github.com/oscartbeaumont/specta/pull/97) with the version of `specta` that is used. I think the doc comments are working in the v2 pre-release versions of specta. I will try it out and then probably publish the fix.

**Comment by MatsDK** [comment]
Fixed in `taurpc@0.2.6`
