### ISSUE TITLE
Built app requires admin perms when installed in C:\Program Files

### ISSUE THREAD

**Issue by yanqui-uxo** [MatsDK/TauRPC#24]
If the program is run without admin perms, it crashes immediately.
I have isolated the problem to this call: `.invoke_handler(create_ipc_handler(ApiImpl.into_handler()))`
I assume it has something to do with exporting types.

**Comment by MatsDK** [comment]
Thanks for reporting, this should be fixed in version `0.2.7`. Now we're only exporting the types on development builds. Hopefully this works for you.

**Comment by yanqui-uxo** [comment]
Fixed, thank you
